### ISSUE TITLE
coroutine中的dummy是什么

### ISSUE THREAD

**Issue by heyxhh** [chenyahui/AnnotatedCode#3]
static void
_save_stack(struct coroutine *C, char *top) {
	// 这个dummy很关键，是求取整个栈的关键
	// 这个非常经典，涉及到linux的内存分布，栈是从高地址向低地址扩展，因此
	// S->stack + STACK_SIZE就是运行时栈的栈底
	// dummy，此时在栈中，肯定是位于最底的位置的，即栈顶
	// top - &dummy 即整个栈的容量
	char dummy = 0;
	assert(top - &dummy <= STACK_SIZE);
	if (C->cap < top - &dummy) {
		free(C->stack);
		C->cap = top-&dummy;
		C->stack = malloc(C->cap);
	}
	C->size = top - &dummy;
	memcpy(C->stack, &dummy, C->size);
}

请问 top - &dummy为什么是整个栈的容量，栈的容量不应该是STACK_SIZE吗？。
dummy的定义为char dummy = 0; 它代表了什么含义。&dummy指的是什么地址呢？

**Comment by heyxhh** [comment]
我自问自答一下：
linux的栈是从高地址到低地址生长的，top = S->stack + STACH_SIZE是运行上下文的栈底
声明char dummy = 0,会将dummy压栈，则dummy的首地址是其没压栈时stack的栈顶
那么，top - &dummy的值为dummy压栈前栈已用空间的大小

**Comment by chenyahui** [comment]
> 我自问自答一下：
> linux的栈是从高地址到低地址生长的，top = S->stack + STACH_SIZE是运行上下文的栈底
> 声明char dummy = 0,会将dummy压栈，则dummy的首地址是其没压栈时stack的栈顶
> 那么，top - &dummy的值为dummy压栈前栈已用空间的大小

@heyxhh 分析的很好，关于coroutine的具体分析可以看我的博客: 《云风 coroutine 协程库源码分析》
https://www.cyhone.com/articles/analysis-of-cloudwu-coroutine/

里面相关细节都有

**Comment by heyxhh** [comment]
> > 我自问自答一下：
> > linux的栈是从高地址到低地址生长的，top = S->stack + STACH_SIZE是运行上下文的栈底
> > 声明char dummy = 0,会将dummy压栈，则dummy的首地址是其没压栈时stack的栈顶
> > 那么，top - &dummy的值为dummy压栈前栈已用空间的大小
> 
> @heyxhh 分析的很好，关于coroutine的具体分析可以看我的博客: 《云风 coroutine 协程库源码分析》
> https://www.cyhone.com/articles/analysis-of-cloudwu-coroutine/
> 
> 里面相关细节都有

好的 多谢分享
