### ISSUE TITLE
中文社区挂了

### ISSUE THREAD

**Issue by beckbikang** [chenyahui/AnnotatedCode#4]
提议项目grpc

**Comment by chenyahui** [comment]
> 提议项目grpc

@beckbikang 有几篇grpc-go的分析文章还在写，欢迎关注~

不过标题里面的 "中文社区挂了" 是什么意思？

**Comment by beckbikang** [comment]
sorry，写issue记录错了项目=。=

dlang的中文社区站点挂了。
